### ISSUE TITLE
ApolloServer 1.1.1 Software Failed Error error 80000003 on Amiga 1200

### ISSUE THREAD

**Issue by youenchene** [ronybeck/ApolloExplorer#2]
![IMG_0094](https://github.com/ronybeck/ApolloExplorer/assets/1607244/9b247736-e787-401a-847d-736440160dc3)

On Apollo 1.1.1 and 1.1.0 (works on 1.0.12)

Config :

- A1200
- WB3.2
- ACA1221

When you launch the server or the tool.

**Comment by ronybeck** [comment]
Thanks for reporting this!  I had some other people report the same problem.  It seems I messed up the compilation of the server.  It  worked on my machines but for most people it crashes just like for you.  I have a fix for this in the next release.  I want to release this tomorrow.  This release also has some PC side fixes as well so it should be better all round.

Sorry about that! :-(  But the fix should be there tomorrow.

**Comment by ronybeck** [comment]
I have released the next version with a new amiga server binary.  Let me know if this improves things for you or not.

**Comment by youenchene** [comment]
Just tested it. It works perfectly. Tx!
