### ISSUE TITLE
Changes of Version 1.1.3?

### ISSUE THREAD

**Issue by halle-saale** [ronybeck/ApolloExplorer#3]
Sorry for bothering in this way, but I have not found any contact address:
what has changed in this version?

And what do you mean by "This marks the first release version of the 1.1.x Series"?
What about previous versions, e.g. 1.1.2?

Thanks!
Daniel from Amiga-News.de
(https://www.amiga-news.de/en/news/AN-2024-01-00063-EN.html)

**Comment by ronybeck** [comment]
Hi Daniel,

Thank you very much for reaching out!   Yes, you are not the first to ask this and so I have updated the release notes.  I will be more descriptive in the future.

I am reachable on the Apollo Team discord server under the name ronybeck.  You can also contact me by email at ronybeck@themenz.biz.  Deutsch geht auch.  :-)

Many thanks!

Rony

**Comment by ronybeck** [comment]
Hi Daniel,

Many thanks for sharing the release on amiga-news.de.  That is very kind.  I read the posts.  One thing to note is that, the software should run on all amigas with enough CPU and ram to run a web browser.  It isn't just for Apollo accelerator based machines to run the software.  I heard from some PiStorm users that it works for them as well as users just running an ACA 1230 68030 accelerator card.

Kind regards,

Rony
